spring:
  application:
    name: SpringSecurityJWT
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity
    username: root
    password: Avtooyna2023
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
      show-sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5Dialect